apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
  namespace: ifunds-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx-test
          image: seagwamaksdevacr.azurecr.io/nginx
          resources:
           requests:
            memory: "128Mi"
            cpu: "250m"
           limits:
            memory: "256Mi"
            cpu: "500m"
          ports:
            - containerPort: 80
