apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb2app-probes
  labels:
    app: bb2app-probes
  namespace: ifunds-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb2app-probes
  template:
    metadata:
      labels:
        app: bb2app-probes
    spec:
      containers:
        - name: bb2app-probes
          image: seagwamaksdevacr.azurecr.io/bb2app:v1
          resources:
           requests:
            memory: "128Mi"
            cpu: "250m"
           limits:
            memory: "256Mi"
            cpu: "500m"
          env:
          - name: PORT
            value: "8080"
          - name: PCF_ENV
            value: "dev"
          ports:
            - containerPort: 8080
          startupProbe:
           tcpSocket:
            port: 8080
           initialDelaySeconds: 30
           periodSeconds: 10
           timeoutSeconds: 10
          livenessProbe:
           tcpSocket:
            port: 8080
           initialDelaySeconds: 20
           periodSeconds: 10
           timeoutSeconds: 10
          readinessProbe:
           tcpSocket:
            port: 8080
           initialDelaySeconds: 30
           periodSeconds: 10
           timeoutSeconds: 10
