apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb2app-probes
  labels:
    app: bb2app-probes
  namespace: ifunds-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb2app-probes
  template:
    metadata:
      labels:
        app: bb2app-probes
    spec:
      containers:
        - name: bb2app-probes
          image: seagwamaksdevacr.azurecr.io/bb2app:v1
          env:
          - name: PORT
            value: "8080"
          - name: PCF_ENV
            value: "dev"
          ports:
            - containerPort: 8080
