apiVersion: v1
kind: Service
metadata:
  name: bb2app-service
  namespace: default
spec:
  ports:
  - nodePort: 32431
    port: 8080
    targetPort: 8080
  selector:
    app: bb2app-probes
  type: ClusterIP
