# This is a basic workflow to help you get started with Actions

name: build project

# Controls when the workflow will run
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["test project"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Scan image
        uses: Azure/container-scan@v0
        with:
         image-name: docker.io/node:alpine3.15
         severity-threshold: CRITICAL
         run-quality-checks: true
