name: GitHub Actions Demo

on: workflow_dispatch

env:
  TEST: test value from workflow
  
jobs:

  Explore-GitHub-Actions-DEV:
  
    runs-on: ubuntu-latest
    environment: DEVELOPMENT
    
    steps:
    
      - run: echo "Value ${{ secrets.SECRET }}."
  
  Explore-GitHub-Actions-UAT:
  
    runs-on: ubuntu-latest
    needs: Explore-GitHub-Actions-DEV
    environment: UAT
    
    steps:
    
      - run: echo "Value ${{ secrets.SECRET }}."
      
  
